import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { SiteLayout } from "@/components/site/SiteLayout";
import { Button } from "@/components/ui/button";
import { DesignImage } from "@/components/site/DesignImage";
import { Chip } from "@/components/site/Chip";
import { useAuth } from "@/hooks/useAuth";
import { currency, formatDate, STATUS_LABEL } from "@/lib/format";
import { myDesignsQuery, myOrdersQuery } from "@/lib/queries";
export const Route=createFileRoute("/account")({head:()=>({meta:[{title:"Your account — Pressworks"},{name:"description",content:"View your Pressworks orders and saved designs."},{property:"og:title",content:"Your account — Pressworks"},{property:"og:description",content:"Your orders and saved garment designs."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Account});
function Account(){const {user,loading}=useAuth();const {data:orders}=useQuery(myOrdersQuery(user?.id));const {data:designs}=useQuery(myDesignsQuery(user?.id));if(loading)return null;if(!user)return <SiteLayout><section className="mx-auto max-w-xl px-5 py-20"><h1 className="text-4xl font-semibold">Your account</h1><p className="mt-4 text-muted-foreground">Sign in to see orders and saved designs.</p><Button asChild className="mt-8"><Link to="/login">Sign in</Link></Button></section></SiteLayout>;return <SiteLayout><section className="mx-auto max-w-[1100px] px-5 py-14"><h1 className="text-4xl font-semibold">Your account</h1><section className="mt-14"><h2 className="text-2xl font-semibold">Orders</h2><div className="mt-5 border-t border-border">{orders?.length?orders.map(o=><article key={o.id} className="grid gap-3 border-b border-border py-5 sm:grid-cols-4 sm:items-center"><div><p className="font-medium">{o.order_number}</p><p className="text-xs text-muted-foreground">{formatDate(o.created_at)}</p></div><p className="text-sm">{o.order_items.length} item{o.order_items.length===1?"":"s"}</p><Chip>{STATUS_LABEL[o.status]}</Chip><p className="sm:text-right font-medium">{currency(Number(o.total))}</p></article>):<p className="py-8 text-muted-foreground">No orders yet.</p>}</div></section><section className="mt-16"><h2 className="text-2xl font-semibold">Saved designs</h2><div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{designs?.length?designs.map(d=><Link key={d.id} to="/customize/$productId" params={{productId:d.product_id}} search={{design:d.id}} className="border border-border bg-card"><DesignImage path={d.preview_thumbnail_url??d.uploaded_image_path} alt="Saved artwork" className="aspect-square w-full object-contain"/><p className="border-t border-border p-4 text-sm">Continue this design</p></Link>):<p className="text-muted-foreground">No saved designs yet.</p>}</div></section></section></SiteLayout>}