import { useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { toast } from "sonner";
import { SiteLayout } from "@/components/site/SiteLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/hooks/useAuth";
import { createOrder } from "@/lib/checkout.functions";
import { currency } from "@/lib/format";
import { cartSubtotal, useCartStore } from "@/stores/cartStore";
export const Route=createFileRoute("/checkout")({head:()=>({meta:[{title:"Checkout — Pressworks"},{name:"description",content:"Add delivery details for your Pressworks order."},{property:"og:title",content:"Checkout — Pressworks"},{property:"og:description",content:"Complete your custom garment order."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Checkout});
function Checkout(){const {user,loading}=useAuth();const lines=useCartStore(s=>s.lines);const clear=useCartStore(s=>s.clear);const submitOrder=useServerFn(createOrder);const navigate=useNavigate();const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const result=await submitOrder({data:{lines:lines.map(l=>({productId:l.productId,designId:l.designId,size:l.size,color:l.color,quantity:l.quantity})),shipping:{full_name:String(f.get("name")),line1:String(f.get("line1")),line2:String(f.get("line2")),city:String(f.get("city")),postal_code:String(f.get("postal")),country:String(f.get("country"))}}});clear();void navigate({to:"/order-confirmation/$orderId",params:{orderId:result.orderId}})}catch(error){toast.error(error instanceof Error?error.message:"Could not place order")}finally{setBusy(false)}}if(loading)return null;if(!user)return <SiteLayout><section className="mx-auto max-w-lg px-5 py-20"><h1 className="text-4xl font-semibold">Sign in to check out</h1><Button asChild className="mt-8"><Link to="/login">Sign in</Link></Button></section></SiteLayout>;if(!lines.length)return <SiteLayout><section className="mx-auto max-w-lg px-5 py-20"><h1 className="text-4xl font-semibold">Your cart is empty</h1><Button asChild className="mt-8"><Link to="/shop">Return to shop</Link></Button></section></SiteLayout>;return <SiteLayout><section className="mx-auto grid max-w-[980px] gap-12 px-5 py-14 lg:grid-cols-[1fr_320px]"><div><h1 className="text-4xl font-semibold">Delivery details</h1><form onSubmit={submit} className="mt-8 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm">Full name<Input name="name" required className="mt-2"/></label><label className="sm:col-span-2 text-sm">Address<Input name="line1" required className="mt-2"/></label><label className="sm:col-span-2 text-sm">Address line 2<Input name="line2" className="mt-2"/></label><label className="text-sm">City<Input name="city" required className="mt-2"/></label><label className="text-sm">Postal code<Input name="postal" required className="mt-2"/></label><label className="sm:col-span-2 text-sm">Country<Input name="country" required className="mt-2"/></label><Button className="sm:col-span-2 mt-3" disabled={busy}>{busy?"Preparing order…":"Continue to payment"}</Button></form></div><aside className="border-t border-border pt-6"><h2 className="font-medium">Order summary</h2>{lines.map(l=><p key={l.key} className="mt-4 flex justify-between text-sm"><span>{l.quantity} × {l.productName}</span><span>{currency(l.quantity*l.unitPrice)}</span></p>)}<p className="mt-6 flex justify-between border-t border-border pt-4 font-medium"><span>Total</span><span>{currency(cartSubtotal(lines))}</span></p><p className="mt-4 text-xs text-muted-foreground">Secure card payment becomes available once payments are connected.</p></aside></section></SiteLayout>}