import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { z } from "zod";
import { toast } from "sonner";
import { GarmentViewer } from "@/components/garment/GarmentViewer";
import { UploadPanel } from "@/components/customizer/UploadPanel";
import { TransformPanel } from "@/components/customizer/TransformPanel";
import { ColorSizeSelector } from "@/components/customizer/ColorSizeSelector";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/useAuth";
import { designQuery, productQuery, signedDesignUrl } from "@/lib/queries";
import { supabase } from "@/integrations/supabase/client";
import { useCustomizerStore } from "@/stores/customizerStore";
import { useCartStore } from "@/stores/cartStore";
export const Route=createFileRoute("/customize/$productId")({validateSearch:(s)=>z.object({color:z.string().optional(),size:z.string().optional(),design:z.string().optional()}).parse(s),head:()=>({meta:[{title:"Design your garment — Pressworks"},{name:"description",content:"Place your artwork on a garment in 3D and save your design."},{property:"og:title",content:"Design your garment — Pressworks"},{property:"og:description",content:"Create a custom garment in the Pressworks 3D studio."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Customize});
function Customize(){const {productId}=Route.useParams();const search=Route.useSearch();const {user}=useAuth();const {data:product}=useQuery(productQuery(productId));const {data:design}=useQuery(designQuery(search.design??null));const state=useCustomizerStore();const add=useCartStore(s=>s.add);const navigate=useNavigate();const [saving,setSaving]=useState(false);useEffect(()=>{if(search.color)state.setColor(search.color);if(search.size)state.setSize(search.size)},[search.color,search.size]);useEffect(()=>{if(!design)return;void signedDesignUrl(design.uploaded_image_path).then(url=>state.hydrate({imageUrl:url,imagePath:design.uploaded_image_path,position:[design.position_x,design.position_y,design.position_z],rotation:design.rotation,scale:design.scale,color:design.garment_color}))},[design]);if(!product)return null;async function save(){if(!user)return void navigate({to:"/login"});if(!state.imagePath)return toast.error("Add your artwork first");setSaving(true);const row={product_id:productId,uploaded_image_path:state.imagePath,position_x:state.position[0],position_y:state.position[1],position_z:state.position[2],rotation:state.rotation,scale:state.scale,garment_color:state.color,preview_thumbnail_url:state.imagePath};const query=search.design?supabase.from("designs").update(row).eq("id",search.design).select("id").single():supabase.from("designs").insert(row).select("id").single();const {data,error}=await query;setSaving(false);if(error)return toast.error(error.message);state.setConfirmed(true);add({productId,productName:product?.name??"Garment",designId:data.id,size:state.size,color:state.color,quantity:1,unitPrice:Number(product?.base_price??0),previewUrl:state.imageUrl});setTimeout(()=>void navigate({to:"/cart"}),650)}return <div className="min-h-screen bg-workshop text-workshop-foreground"><header className="flex h-16 items-center justify-between border-b border-workshop-border px-5"><Link to="/" className="text-lg font-semibold">Pressworks</Link><Link to="/product/$id" params={{id:productId}} className="text-sm text-workshop-foreground/60">Back to garment</Link></header><main className="grid min-h-[calc(100vh-4rem)] lg:grid-cols-[1fr_360px]"><div className="min-h-[52vh]"><GarmentViewer className="h-full min-h-[52vh]" category={product.category} color={state.color} imageUrl={state.imageUrl} position={state.position} rotation={state.rotation} scale={state.scale} settle={state.confirmed}/></div><aside className="border-l border-workshop-border bg-workshop-panel p-6"><h1 className="text-3xl font-semibold">Make it yours</h1><div className="mt-8 space-y-8"><UploadPanel userId={user?.id??null}/><TransformPanel/><ColorSizeSelector colors={product.available_colors}/></div><Button className="mt-10 w-full" onClick={save} disabled={saving}>{saving?"Saving…":"Save design"}</Button></aside></main></div>}